network:
  # externalHost: SET YOUR EXTERNAL IP HERE (e.g., 12.34.56.78)
  externalPort: 6688
  port: 6688
  bootstrapNodes:
    - /ip4/127.0.0.1/tcp/4689/p2p/12D3KooWBX8HJvuQ2wEabZ78Uo2oRuHySVB4ppMxFeB8DKF7jgRe


api:
  gasStation:
    defaultGas: 5000000000000
  web3port: 6345
  port: 6333

system:
  httpStatsPort: 6933
  httpAdminPort: 6119


chain:
  id: 233333
  evmNetworkID: 233333
  producerPrivKey: TODO_REPLACE_WITH_YOUR_OWN_SK_OR_ADDRESS
  # If you are a delegate, make sure producerPrivKey is the key for the operator address you have registered.
  # producerPrivKey: SET YOUR PRIVATE KEY HERE (e.g., 96f0aa5e8523d6a28dc35c927274be4e931e74eaa720b418735debfcbfe712b8)
  chainDBPath: "/var/data/chain6.db"
  trieDBPath: "/var/data/trie6.db"
  indexDBPath: "/var/data/index6.db"
  bloomfilterIndexDBPath: "/var/data/bloomfilter.index6.db"
  candidateIndexDBPath: "/var/data/candidate.index6.db"
  stakingIndexDBPath: "/var/data/staking.index6.db"
  maxCacheSize: 1000
  committee:
    gravityChainAPIs:
      # please change the infura key to your key (e.g., https://mainnet.infura.io/v3/YOUR_KEY)
      - https://api.blockeden.xyz/eth/NOT_NEEDED
    numOfRetries: 20
    paginationSize: 255
    cacheSize: 1000
  gravityChainDB:
    dbPath: "/var/data/poll6.db"
    numRetries: 8

actPool:
  minGasPrice: "1000000000000"
  maxNumActsPerAcct: 100
  maxNumActsPerPool: 32000
  maxGasLimitPerPool: 320000000
  actionExpiry: 5m

consensus:
  scheme: ROLLDPOS
  rollDPoS:
    fsm:
      unmatchedEventTTL: 3s
      unmatchedEventInterval: 100ms
      acceptBlockTTL: 4s
      acceptProposalEndorsementTTL: 2s
      acceptLockEndorsementTTL: 2s
    delay: 10s
    consensusDBPath: "/var/data/consensus6.db"

blockSync:
  interval: 10s
  bufferSize: 400
  maxRepeat: 3
  repeatDecayStep: 3

log:
  zap:
    level: info
    encoding: json
    disableStacktrace: true
    outputPaths: ["stderr", "stdout"]
    errorOutputPaths: ["stderr", "stdout"]
  stderrRedirectFile: /var/log/s6.log
  stdLogRedirect: true
